version: 2
jobs:
  build:
    working_directory: ~/cci-phoenix
    docker:
      - image: elixir:1.7
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: cd app ; mix deps.get
      - run: cd app ; DB_HOST=localhost mix test